<?php

namespace SmartPsyBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * QuestionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QuestionRepository extends EntityRepository
{

    public  function findQuestion($test){
        $query = $this->createQueryBuilder('a')
            ->andWhere('a.test =:test')
            ->setParameter('test', $test);
        return $query->getQuery()->getResult();
    }


}
