<?php

namespace SmartPsyBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TestAffecterRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TestAffecterRepository extends EntityRepository
{
}
