<?php

namespace UserBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TestRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{

    public  function findPatient(){
        $query = $this->createQueryBuilder('a')
            ->andWhere('a.roles LIKE :test')
            ->setParameter('test', '%ROLE_PATION%');
        return $query->getQuery()->getResult();
    }


}
